"""add api_key to tenant

Revision ID: 047385ec3dd8
Revises: e8110756c329
Create Date: 2026-03-08 11:07:15.362369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047385ec3dd8'
down_revision: Union[str, None] = 'e8110756c329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.drop_column('tenants', 'api_key')
    # ### end Alembic commands ###
