"""add_tenant_cascade_deletes

Revision ID: fc007e311b38
Revises: a67fa724b9d8
Create Date: 2026-03-08 20:25:06.467322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc007e311b38'
down_revision: Union[str, None] = 'a67fa724b9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_tenant_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_kb_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('knowledge_bases_tenant_id_fkey'), 'knowledge_bases', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_bases', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('usage_logs_tenant_id_fkey'), 'usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'usage_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key(op.f('usage_logs_tenant_id_fkey'), 'usage_logs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_bases_tenant_id_fkey'), 'knowledge_bases', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_kb_id_fkey'), 'documents', 'knowledge_bases', ['kb_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_tenant_id_fkey'), 'conversations', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
